export GBT_CARS='Status, Hostname, Dir, Kubectl, Git, Sign'
export GBT_CAR_STATUS_FORMAT=' {{ Symbol }} {{ Signal }} '
export GBT_CAR_HOSTNAME_FORMAT=' {{ User }} '
export GBT_CAR_DIR_DEPTH='10'
export GBT_CAR_DIR_BG="yellow"
export GBT_CAR_DIR_FG="black"
export GBT_CAR_KUBECTL_BG="blue"
export GBT_CAR_KUBECTL_FORMAT=' {{ Icon }} {{Context}}:{{Namespace}} '
export GBT_CAR_KUBECTL_NAMESPACE_FM="bold"
export GBT_CAR_SIGN_WRAP="1"