# Repositories
tap "aquasecurity/trivy"
tap "go-task/tap"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"
tap "xwmx/taps"

# Packages
brew "aquasecurity/trivy/trivy"
brew "awscli"
brew "direnv"
brew "docker"
brew "fzf"
brew "git-flow"
brew "go-task/tap/go-task"
brew "helm"
brew "jq"
brew "kind"
brew "kubectl"
brew "kustomize"
brew "minikube"
brew "packer"
brew "wget"
brew "xwmx/taps/hosts"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# MacOS Applications
cask "font-meslo-for-powerline"
cask "iterm2"
cask "gitkraken"
cask "gpg-suite"
cask "logmein-client"
cask "microsoft-teams"
cask "nitrokey"
cask "teamviewer"
cask "vagrant"