# Repositories
tap "caskroom/cask"
tap "caskroom/fonts"
tap "homebrew/core"
tap "homebrew/bundle"
tap "go-task/tap"
tap "hairyhenderson/tap"

# Packages
brew "docker-ls"
brew "dockutil"
brew "git"
brew "git-flow"
brew "go"
brew "go-task"
brew "hadolint"
brew "hairyhenderson/tap/gomplate"
brew "httpie"
brew "jq"
brew "kubernetes-helm"
brew "kube-ps1"
brew "wget"
brew "yq"
brew "zsh"
brew "zsh-completions"

# MacOS Applications
cask "anytrans"
cask "dashlane"
cask "docker"
cask "gitify"
cask "gitkraken"
cask "minikube"
cask "toggl"
cask "virtualbox"
